/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexcopyRouteImport } from './routes/index copy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellSupabaseCallRouteImport } from './routes/_shell.supabase-call'

const IndexcopyRoute = IndexcopyRouteImport.update({
  id: '/index copy',
  path: '/index copy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSupabaseCallRoute = ShellSupabaseCallRouteImport.update({
  id: '/supabase-call',
  path: '/supabase-call',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/index copy': typeof IndexcopyRoute
  '/supabase-call': typeof ShellSupabaseCallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/index copy': typeof IndexcopyRoute
  '/supabase-call': typeof ShellSupabaseCallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/about': typeof AboutRoute
  '/index copy': typeof IndexcopyRoute
  '/_shell/supabase-call': typeof ShellSupabaseCallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/index copy' | '/supabase-call'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/index copy' | '/supabase-call'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/about'
    | '/index copy'
    | '/_shell/supabase-call'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AboutRoute: typeof AboutRoute
  IndexcopyRoute: typeof IndexcopyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index copy': {
      id: '/index copy'
      path: '/index copy'
      fullPath: '/index copy'
      preLoaderRoute: typeof IndexcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/supabase-call': {
      id: '/_shell/supabase-call'
      path: '/supabase-call'
      fullPath: '/supabase-call'
      preLoaderRoute: typeof ShellSupabaseCallRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellSupabaseCallRoute: typeof ShellSupabaseCallRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSupabaseCallRoute: ShellSupabaseCallRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AboutRoute: AboutRoute,
  IndexcopyRoute: IndexcopyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
